version: "3"

services: 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-nerdstore
    environment:
      RABBITMQ_DEFAULT_USER: "nerdstore"
      RABBITMQ_DEFAULT_PASS: "nerdstore"
    ports:
      - "5672:5672"
      - "15672:15672"

  sql-server:
    image: brspontes/nerdstore-sql-server:latest
    container_name: nerdstore-sql-server
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"

  web-mvc:
    image: brspontes/nerdstore-web-mvc:latest
    container_name: nerdstore-web-mvc
    build:
      context: ../src
      dockerfile: ./Web/NerdStore.Enterprise.Web/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    depends_on:
      - api-catalogo
      - api-identidade
      - api-bff-compras
  
  api-identidade:
    image: brspontes/nerdstore-api-identidade:latest
    container_name: nerdstore-api-identidade
    build:
      context: ../src
      dockerfile: ./Services/NerdStore.Enterprise.Identidade.Api/Dockerfile
    ports:
      - "5101:5101"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5101
    depends_on:
      - rabbitmq
      - sql-server

  api-carrinho:
    image: brspontes/nerdstore-api-carrinho:latest
    container_name: nerdstore-api-carrinho
    build:
      context: ../src
      dockerfile: ./Services/NerdStore.Enterprise.Carrinho.API/Dockerfile
    ports:
      - "5201:5201"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5201
    depends_on:
      - rabbitmq
      - api-identidade
      - sql-server
    
  api-catalogo:
    image: brspontes/nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    build:
      context: ../src
      dockerfile: ./Services/NerdStore.Enterprise.Catalogo.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5301
    depends_on: 
      - rabbitmq

  api-cliente:
    image: brspontes/nerdstore-api-cliente:latest
    container_name: nerdstore-api-cliente
    build:
      context: ../src
      dockerfile: ./Services/NerdStore.Enterprise.Cliente.API/Dockerfile
    ports:
      - "5401:5401"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5401
    depends_on: 
      - rabbitmq
      - api-identidade
      - sql-server

  api-bff-compras:
    image: brspontes/nerdstore-api-bff-compras:latest
    container_name: nerdstore-api-bff-compras
    build:
      context: ../src
      dockerfile: ./ApiGateways/NerdStore.Enterprise.Bff.Compras/Dockerfile
    ports:
      - "5501:5501"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5501
    depends_on: 
      - rabbitmq
      - api-identidade
      - api-carrinho
      - api-pagamento
      - api-pedido

  api-pagamento:
    image: brspontes/nerdstore-api-pagamento:latest
    container_name: nerdstore-api-pagamento
    build:
      context: ../src
      dockerfile: ./Services/NerdStore.Enterprise.Pagamento.API/Dockerfile
    ports:
      - "5601:5601"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5601
    depends_on: 
      - rabbitmq
      - api-identidade
      - api-pedido
      - sql-server

  api-pedido:
    image: brspontes/nerdstore-api-pedido:latest
    container_name: nerdstore-api-pedido
    build:
      context: ../src
      dockerfile: ./Services/NerdStore.Enterprise.Pedido.API/Dockerfile
    ports:
      - "5701:5701"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5701
    depends_on: 
      - rabbitmq
      - api-identidade
      - sql-server

  nerdstore-server:
    image: brspontes/nerdstore-server:latest
    container_name: nerdstore-server
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-mvc