version: "3"

services: 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-nerdstore
    environment:
      RABBITMQ_DEFAULT_USER: "nerdstore"
      RABBITMQ_DEFAULT_PASS: "nerdstore"
    ports:
      - "5672:5672"
      - "15672:15672"

  sql-server:
    image: brspontes/nerdstore-sql-server:latest
    container_name: nerdstore-sql-server
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"


  web-mvc:
    image: brspontes/nerdstore-web-mvc:latest
    container_name: nerdstore-web-mvc
    build:
      context: ../src
      dockerfile: ./Web/NerdStore.Enterprise.Web/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    depends_on:
      - api-catalogo
  
  api-catalogo:
    image: brspontes/nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    build:
      context: ../src
      dockerfile: ./Services/NerdStore.Enterprise.Catalogo.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5301
    depends_on: 
      - rabbitmq